name: ethiojobs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
  - assets/search.svg
  - assets/ethio_logo.png
  - assets/search_icon.svg
  - assets/search20.svg
  - assets/ahadu_logo.png
  - assets/amref_logo.png
  - assets/coca_logo.png
  - assets/dashin_logo.png
  - assets/komari_logo.png
  - assets/mariestops_logo.png
  - assets/medicalcorps_logo.png
  - assets/unilever_logo.png
  - assets/zemen_logo.png
  - assets/savechild_logo.png
  - assets/actionhunger_logo.jpg
  - assets/bgi_logo.png
  - assets/catholic_logo.jpg
  - assets/care_logo.png
  - assets/islamic_logo.jpeg
  - assets/medicalteams_logo.jpg
  - assets/people_logo.png
  - assets/mercy_logo.png
  uses-material-design: true

  fonts:
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-Black.ttf
          weight: 900
        - asset: fonts/Outfit-Bold.ttf
          weight: 700
        - asset: fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: fonts/Outfit-Light.ttf
          weight: 300
        - asset: fonts/Outfit-Medium.ttf
          weight: 500
        - asset: fonts/Outfit-Regular.ttf
          weight: 400
        - asset: fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: fonts/Outfit-Thin.ttf
          weight: 100
          

    - family: UbuntuCondensed
      fonts:
        - asset: fonts/UbuntuCondensed-Regular.ttf

   

